cc_test(
    name = "cnv_test",
    size = "small",
    srcs = ["cnv_test.cc"],
    deps = [
        "@gtest//:main",
        "//src:cctz",
    ],
)

cc_test(
    name = "fmt_test",
    size = "small",
    srcs = ["fmt_test.cc"],
    deps = [
        "@gtest//:main",
        "//src:cctz",
    ],
)
