#!/usr/bin/env bash

TOP_DIR=$(git rev-parse --show-toplevel)

# Format all the C and C++ code.
find $TOP_DIR \
     -iname '*.c' \
  -o -iname '*.h' \
  -o -iname '*.cc' \
  -o -iname '*.cpp' \
  -o -iname '*.c++' \
  -o -iname '*.cxx' \
  -o -iname '*.hpp' \
  -o -iname '*.hxx' \
  -o -iname '*.h++' \
  -o -iname '*.h.in' \
    | xargs -P8 clang-format -i --style=file

# Format all the build files.
buildifier -r $TOP_DIR
