cc_binary(
    name = "classic",
    srcs = ["classic.cc"],
)

cc_binary(
    name = "epoch_shift",
    srcs = ["epoch_shift.cc"],
    deps = [
        "//src:cctz",
    ],
)

cc_binary(
    name = "hello",
    srcs = ["hello.cc"],
    deps = [
        "//src:cctz",
    ],
)

cc_binary(
    name = "example1",
    srcs = ["example1.cc"],
    deps = [
        "//src:cctz",
    ],
)

cc_binary(
    name = "example2",
    srcs = ["example2.cc"],
    deps = [
        "//src:cctz",
    ],
)

cc_binary(
    name = "example3",
    srcs = ["example3.cc"],
    deps = [
        "//src:cctz",
    ],
)

cc_binary(
    name = "example4",
    srcs = ["example4.cc"],
    deps = [
        "//src:cctz",
    ],
)
